# tasks file
---
- name: configure | systemd | update script
  template:
    src: etc/systemd/system/redis-server.service.j2
    dest: "/etc/systemd/system/{{ redis_instance_service }}.service"
    owner: root
    group: root
    mode: 0644
  register: _update_systemd_script
  notify: restart redis-server
  tags:
    - redis-configure-systemd-update

- name: configure | systemd | reload
  systemd:
    daemon_reload: true
  when: _update_systemd_script is changed
  tags:
    - redis-configure-systemd-reload
