# tasks file for redis
---
- name: configure | stat directories
  stat:
    path: "{{ item }}/"
  register: stat_directories
  with_items:
    - "{{ redis_configuration_file | dirname }}"
    - "{{ redis_logfile | dirname }}"
    - "{{ redis_dir }}"
  when: item != ''
  tags:
    - redis-configure-directories
    - redis-configure-directories-stat

- name: configure | create directories
  file:
    path: "{{ item.item }}"
    state: directory
    owner: "{{ redis_system_user }}"
    group: "{{ redis_system_group }}"
    mode: 0755
  with_items: "{{ stat_directories.results }}"
  when: item.stat is defined and item.stat.exists == false
  tags:
    - redis-configure-directories
    - redis-configure-directories-create

- name: configure | update configuration file
  template:
    src: etc/redis/redis.conf.j2
    dest: "{{ redis_configuration_file }}"
    owner: root
    group: root
    mode: 0644
  notify: "restart {{ redis_instance_name_full }}"
  tags:
   - redis-configure-configuration
