# tasks file for redis
---
- name: install | src | dependencies
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: true
    cache_valid_time: "{{ apt_update_cache_valid_time | default(3600) }}"
  with_items: "{{ redis_dependencies }}"
  tags:
    - redis-install-src-dependencies

- name: install | src | create (checkout) directory
  file:
    path: "{{ redis_checkout_path }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  tags:
    - redis-install-src-dependencies-checkout
    - redis-install-src-dependencies-checkout-directory

- name: install | src | checkout repository
  git:
    repo: https://github.com/antirez/redis.git
    dest: "{{ redis_checkout_path }}"
    version: "{{ redis_version }}"
    force: true
  register: git_checkout
  tags:
    - redis-install-src-dependencies-checkout
    - redis-install-src-dependencies-checkout-repository

- name: install | src | make
  command: make -j{{ ansible_processor_cores + 1 }}
  args:
    chdir: "{{ redis_checkout_path }}"
  when: git_checkout | changed
  tags:
    - redis-install-src-build

- name: install | src | remove (distro version)
  apt:
    name: redis-server
    state: absent
  tags:
    - redis-install-src-remove-distro

- name: install | src | install
  command: make PREFIX=/usr install
  args:
    chdir: "{{ redis_checkout_path }}"
  when: git_checkout | changed
  notify: restart redis-server
  tags:
    - redis-install-src-install

- name: install | src | add redis user
  user:
    name: "{{ redis_system_user }}"
    comment: 'redis server'
    home: /nonexistent
    shell: /bin/false
    system: yes
  tags:
    - redis-install-src-user

- name: install | src | cleanup build
  shell: git reset --hard && git clean -d -x -f
  args:
    chdir: "{{ redis_checkout_path }}"
  when: git_checkout | changed
  tags:
    - redis-install-src-cleanup
