# tasks file
---
- name: install | ppa | add repository and install its signing key
  apt_repository:
    repo: 'ppa:chris-lea/redis-server'
    update_cache: true
    mode: 0644
  tags:
    - redis-install-ppa-add-repository

- name: install | ppa | latest
  apt:
    name: redis-server
    state: "{{ apt_install_state | default('latest') }}"
  tags:
    - redis-install-ppa-latest
