# tasks file for redis
---
- name: kernel | set system overcommit policy
  sysctl:
    name: vm.overcommit_memory
    value: "{{ redis_vm_overcommit_memory }}"
    reload: true
    state: present
  when: redis_vm_overcommit_memory != false
  tags:
    - redis-kernel-vm-overcommit-memory
