# tasks file
---
- name: include variables
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "_{{ ansible_facts['distribution_release'] }}.yml"
    - "_{{ ansible_facts['distribution'] | lower }}.yml"
    - _default.yml
  tags:
    - configuration
    - redis
    - redis-include-variables

- name: install | method | check
  ansible.builtin.fail:
    msg: "Install method {{ redis_install_method }} is not supported"
  when: redis_install_method | string not in redis_install_methods_supported
  tags:
    - configuration
    - redis
    - redis-install-method
    - redis-install-method-check

- name: install ppa
  ansible.builtin.import_tasks: install-ppa.yml
  when: redis_install_method == 'ppa'
  tags:
    - configuration
    - redis
    - redis-install
    - redis-install-ppa

- name: install src
  ansible.builtin.import_tasks: install-src.yml
  when: redis_install_method != 'ppa'
  tags:
    - configuration
    - redis
    - redis-install
    - redis-install-src

- name: configure
  ansible.builtin.import_tasks: configure.yml
  tags:
    - configuration
    - redis
    - redis-configure

- name: configure | version | get
  ansible.builtin.command: >
    redis-server --version
  register: _redis_binary_version
  changed_when: false
  tags:
    - configuration
    - redis
    - redis-configure
    - redis-configure-version-get

- name: configure initd
  ansible.builtin.import_tasks: configure-initd.yml
  when: ansible_service_mgr != 'systemd'
  tags:
    - configuration
    - redis
    - redis-configure
    - redis-configure-initd

- name: configure systemd
  ansible.builtin.import_tasks: configure-systemd.yml
  when: ansible_service_mgr == 'systemd'
  tags:
    - configuration
    - redis
    - redis-configure
    - redis-configure-systemd

- name: kernel
  ansible.builtin.import_tasks: kernel.yml
  tags:
    - configuration
    - redis
    - redis-kernel

- name: start and enable service
  ansible.builtin.service:
    name: "{{ redis_instance_service }}"
    state: "{{ service_default_state | default('started') }}"
    enabled: "{{ service_default_enabled | default(true) | bool }}"
  tags:
    - configuration
    - redis
    - redis-start-enable-service
