# tasks file for redis
---
- include: install.yml
  tags:
    - configuration
    - redis
    - redis-install

- include: configure.yml
  tags:
    - configuration
    - redis
    - redis-configure

- include: configure-initd.yml
  when: ansible_distribution_version | version_compare('15.04', '<')
  tags:
    - configuration
    - redis
    - redis-configure
    - redis-configure-initd

- include: configure-systemd.yml
  when: ansible_distribution_version | version_compare('15.04', '>=')
  tags:
    - configuration
    - redis
    - redis-configure
    - redis-configure-systemd

- include: kernel.yml
  tags:
    - configuration
    - redis
    - redis-kernel

- name: start and enable service
  service:
    name: "{{ redis_instance_service }}"
    state: started
    enabled: true
  tags:
    - configuration
    - redis
    - redis-start-enable-service
