# tasks file for redis
---
- include: install.yml
  tags:
    - configuration
    - redis
    - redis-install

- include: configure.yml
  tags:
    - configuration
    - redis
    - redis-configure

- include: kernel.yml
  tags:
    - configuration
    - redis
    - redis-kernel

- name: start and enable service
  service:
    name: "{{ redis_instance_service }}"
    state: started
    enabled: true
  tags:
    - configuration
    - redis
    - redis-start-enable-service
